"""
Script: fetch_recently_played.py
================================
Purpose:
    Fetches live listening history via the Spotify Web API `/v1/me/player/recently-played` endpoint using OAuth.
    Formats pulled events into the standardized schema and drops them into the landing zone (`output/raw/dt=YYYY-MM-DD/events.json`).

Spotify API Quota & Security Compliance:
    - Restricted to maximum 5 registered test users (Feb 2026 Developer Mode limits).
    - Uses OAuth 2.0 Authorization Code flow for secure authorization.
    - Tags output events with `source: "real_api"`.

Synthetic persona rows:
    After the real events land, this script also generates the synthetic_persona_matched
    events (users 02-05) for the same days, via generate_data_v2.generate_for_days(). The
    purely synthetic filler users are still generated by generate_data_v2.py itself.
    Each command only replaces its own rows in a partition, never the other's or real ones.
    Days that already have persona-matched rows are left alone (no regeneration, no file
    churn); pass --regenerate-synthetic to replace them. Pass --no-synthetic to skip the step.

By-date fetch:
    --date / --start --end pull only that UTC date range from the API, for incremental or
    backfill work, and generate the persona rows for every day in the range. Spotify's
    recently-played endpoint only keeps roughly the last 50 plays, so a date that has
    already scrolled out of that window returns nothing (the script warns when it happens).

Usage:
    python3 scripts/fetch_recently_played.py --user-id user_real_01 --login     # One-time login OAuth
    python3 scripts/fetch_recently_played.py --user-id user_real_01            # Ongoing scheduled pull
    python3 scripts/fetch_recently_played.py --user-id user_real_01 --date 2026-10-02
    python3 scripts/fetch_recently_played.py --user-id user_real_01 --start 2026-10-01 --end 2026-10-03
"""

import argparse
import base64
import hashlib
import json
import os
import sys
import time
import urllib.parse
import urllib.request
import webbrowser
from datetime import datetime, timedelta, timezone
from http.server import BaseHTTPRequestHandler, HTTPServer


def load_env(env_path=".env"):
    """Load environment variables from a .env file."""
    config = {}
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    k, v = line.split("=", 1)
                    config[k.strip()] = v.strip().strip("'\"")
    return config


def get_spotify_credentials(env_path=".env"):
    """Retrieve Client ID and Client Secret from environment or .env file."""
    env_vars = load_env(env_path)

    client_id = (
        os.getenv("SPOTIFY_CLIENT_ID")
        or os.getenv("CLIENT_ID")
        or env_vars.get("Client_ID")
        or env_vars.get("SPOTIFY_CLIENT_ID")
        or env_vars.get("CLIENT_ID")
    )
    client_secret = (
        os.getenv("SPOTIFY_CLIENT_SECRET")
        or os.getenv("CLIENT_SECRET")
        or env_vars.get("Client_secret")
        or env_vars.get("SPOTIFY_CLIENT_SECRET")
        or env_vars.get("CLIENT_SECRET")
    )

    return client_id, client_secret


def get_token_file_path(user_id):
    """Returns the token cache file path for a user."""
    return f".spotify_tokens_{user_id}.json"


def save_tokens(user_id, token_data):
    """Save token dict to local JSON cache."""
    path = get_token_file_path(user_id)
    if "expires_in" in token_data:
        token_data["expires_at"] = time.time() + token_data["expires_in"] - 60
    with open(path, "w", encoding="utf-8") as f:
        json.dump(token_data, f, indent=2)
    print(f"Tokens saved successfully to {path}")


def load_tokens(user_id):
    """Load cached token dict for a user."""
    path = get_token_file_path(user_id)
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    return None


class OAuthCallbackHandler(BaseHTTPRequestHandler):
    """HTTP Request Handler for OAuth redirect callback."""
    code = None
    error = None

    def do_GET(self):
        parsed = urllib.parse.urlparse(self.path)
        params = urllib.parse.parse_qs(parsed.query)

        if "code" in params:
            OAuthCallbackHandler.code = params["code"][0]
            message = "<h1>Authorization Successful!</h1><p>You can close this window and return to your terminal.</p>"
            status_code = 200
        else:
            OAuthCallbackHandler.error = params.get("error", ["Unknown error"])[0]
            message = f"<h1>Authorization Failed</h1><p>Error: {OAuthCallbackHandler.error}</p>"
            status_code = 400

        self.send_response(status_code)
        self.send_header("Content-Type", "text/html")
        self.end_headers()
        self.wfile.write(message.encode("utf-8"))

    def log_message(self, format, *args):
        return


def run_oauth_login(client_id, client_secret, user_id, port=8888):
    """Interactively log in user via browser OAuth flow."""
    redirect_uri = f"http://127.0.0.1:{port}/callback"
    scope = "user-read-recently-played"

    auth_params = {
        "client_id": client_id,
        "response_type": "code",
        "redirect_uri": redirect_uri,
        "scope": scope,
        "show_dialog": "true",
    }
    auth_url = "https://accounts.spotify.com/authorize?" + urllib.parse.urlencode(auth_params)

    print("\n" + "=" * 60)
    print(f"Spotify OAuth Authorization for user: {user_id}")
    print("=" * 60)
    print("Opening your web browser for Spotify authentication...")
    print(f"If it does not open automatically, visit:\n{auth_url}\n")

    webbrowser.open(auth_url)

    server_address = ("127.0.0.1", port)
    httpd = HTTPServer(server_address, OAuthCallbackHandler)
    httpd.handle_request()

    if OAuthCallbackHandler.error:
        print(f"OAuth Login failed: {OAuthCallbackHandler.error}")
        sys.exit(1)

    auth_code = OAuthCallbackHandler.code
    if not auth_code:
        print("Failed to receive authorization code from Spotify.")
        sys.exit(1)

    print("Authorization code received. Requesting access & refresh tokens...")

    token_url = "https://accounts.spotify.com/api/token"
    body = urllib.parse.urlencode({
        "grant_type": "authorization_code",
        "code": auth_code,
        "redirect_uri": redirect_uri,
    }).encode("utf-8")

    auth_header = base64.b64encode(f"{client_id}:{client_secret}".encode("utf-8")).decode("utf-8")
    req = urllib.request.Request(
        token_url,
        data=body,
        headers={
            "Authorization": f"Basic {auth_header}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST"
    )

    try:
        with urllib.request.urlopen(req) as resp:
            token_data = json.loads(resp.read().decode("utf-8"))
            save_tokens(user_id, token_data)
            return token_data
    except Exception as e:
        print(f"Error exchanging token: {e}")
        sys.exit(1)


def refresh_access_token(client_id, client_secret, user_id, refresh_token):
    """Refresh an expired Spotify access token using the refresh_token."""
    token_url = "https://accounts.spotify.com/api/token"
    body = urllib.parse.urlencode({
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    }).encode("utf-8")

    auth_header = base64.b64encode(f"{client_id}:{client_secret}".encode("utf-8")).decode("utf-8")
    req = urllib.request.Request(
        token_url,
        data=body,
        headers={
            "Authorization": f"Basic {auth_header}",
            "Content-Type": "application/x-www-form-urlencoded",
        },
        method="POST"
    )

    try:
        with urllib.request.urlopen(req) as resp:
            new_tokens = json.loads(resp.read().decode("utf-8"))
            if "refresh_token" not in new_tokens:
                new_tokens["refresh_token"] = refresh_token
            save_tokens(user_id, new_tokens)
            return new_tokens
    except Exception as e:
        print(f"Error refreshing token for user {user_id}: {e}")
        sys.exit(1)


def fetch_recently_played_api(access_token, limit=50, before=None):
    """Call Spotify API GET /v1/me/player/recently-played.

    `before` is a Unix-ms cursor: only plays strictly before it are returned.
    """
    url = f"https://api.spotify.com/v1/me/player/recently-played?limit={limit}"
    if before is not None:
        url += f"&before={int(before)}"
    req = urllib.request.Request(
        url,
        headers={"Authorization": f"Bearer {access_token}"},
        method="GET"
    )
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        print(f"Spotify API Error: {e}")
        sys.exit(1)


def parse_played_at(ts):
    return datetime.fromisoformat(ts.replace("Z", "+00:00")).astimezone(timezone.utc)


def fetch_items_for_window(access_token, start, end, max_pages=10):
    """Plays with start <= played_at < end (UTC datetimes), paging backwards with the
    `before` cursor. Returns (items, history_reaches_start): False means the API ran
    out of history before reaching `start`, so the earliest part of the window is
    simply not available any more."""
    before = int(end.timestamp() * 1000)
    items, reached = [], False
    for _ in range(max_pages):
        data = fetch_recently_played_api(access_token, before=before)
        page = data.get("items", [])
        if not page:
            break
        items.extend(page)
        if parse_played_at(page[-1]["played_at"]) < start:
            reached = True
            break
        cursor = (data.get("cursors") or {}).get("before")
        if not cursor:
            break
        before = int(cursor)
    kept = [i for i in items if start <= parse_played_at(i["played_at"]) < end]
    return kept, reached


def normalize_utc_timestamp(ts):
    """'2026-09-17T20:20:03.123Z' -> '2026-09-17T20:20:03Z'.

    The API adds milliseconds; the exports and the generator use whole seconds
    in UTC. played_at is part of the dedup key and the event_id, so the same
    play from an export and an API pull only matches if the format does.
    """
    parsed = datetime.fromisoformat(ts.replace("Z", "+00:00"))
    return parsed.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def transform_api_item(item, user_id):
    """Transform API recently-played item to standard medallion schema.

    Note on unavailable fields:
      - ms_played: the /recently-played endpoint does not return how much was
        actually listened to, only track duration_ms. Project decision: record
        the full track duration as ms_played (i.e. assume a complete play) and
        tag the row with ms_played_source = "duration_ms_estimate" so the
        estimate stays distinguishable from real export values. Consequence:
        every real_api play looks 100% complete, so exclude real_api rows from
        completion-rate / skip metrics downstream.
      - skipped: the endpoint has no skip signal. null means unknown, not False.
      - device_type: available only if the play context carries a device object;
        otherwise null.  Do NOT default to "mobile".
    """
    track = item.get("track", {})
    track_uri = track.get("uri") or f"spotify:track:{track.get('id')}"
    duration_ms = track.get("duration_ms")  # may be missing/0 for local files

    if not item.get("played_at") or not track_uri:
        return None
    played_at = normalize_utc_timestamp(item["played_at"])

    # The item's `context` is what was playing (playlist/album/artist), not the
    # device, so the endpoint gives no device signal: stay null.
    device_type = None  # unknown — do not fabricate

    h = hashlib.sha256(f"{user_id}_{played_at}_{track_uri}".encode("utf-8")).hexdigest()[:12]
    event_id = f"evt_api_{h}"

    return {
        "event_id": event_id,
        "user_id": user_id,
        "track_id": track_uri,
        "played_at": played_at,
        "ms_played": duration_ms or None,   # estimate: assumes a full play (see docstring)
        "ms_played_source": "duration_ms_estimate" if duration_ms else None,
        "skipped": None,        # not provided by /recently-played; null = unknown
        "device_type": device_type,  # null until a real device signal is available
        "source": "real_api"
    }



def write_or_merge_partition(day_str, new_events, output_dir):
    """Merge API events into the landing zone daily partition file. Returns a dict with
    the number added, whether the file is new, its total row count and its path."""
    partition_dir = os.path.join(output_dir, f"dt={day_str}")
    os.makedirs(partition_dir, exist_ok=True)
    file_path = os.path.join(partition_dir, "events.json")

    existing_events = []
    existed = os.path.exists(file_path)
    if existed:
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                existing_events = json.load(f)
        except Exception as exc:
            # Fail loudly rather than silently treating an unreadable file as
            # empty: overwriting it would destroy any real rows already merged in.
            raise IOError(
                f"Cannot read existing partition {file_path} \u2014 refusing to "
                f"overwrite to avoid data loss. Fix or remove the file first. "
                f"Original error: {exc}"
            ) from exc

    existing_keys = {
        (e.get("user_id"), e.get("played_at"), e.get("track_id"))
        for e in existing_events
    }

    added_count = 0
    for evt in new_events:
        key = (evt.get("user_id"), evt.get("played_at"), evt.get("track_id"))
        if key not in existing_keys:
            existing_events.append(evt)
            existing_keys.add(key)
            added_count += 1

    if added_count or not existed:
        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(existing_events, f, indent=2)

    return {"added": added_count, "created": not existed, "total": len(existing_events), "path": file_path}


def has_persona_rows(output_dir, day_str):
    """True if that day's partition already holds synthetic_persona_matched rows."""
    path = os.path.join(output_dir, f"dt={day_str}", "events.json")
    if not os.path.exists(path):
        return False
    try:
        with open(path, "r", encoding="utf-8") as f:
            return any(e.get("source") == "synthetic_persona_matched" for e in json.load(f))
    except Exception as exc:
        raise IOError(f"Cannot read existing partition {path} \u2014 refusing to continue. "
                      f"Original error: {exc}") from exc


def process_live_api_fetch(user_id, login=False, env_path=".env", output_dir="output/raw",
                           start_day=None, end_day=None, with_synthetic=True, seed=None,
                           regenerate_synthetic=False):
    client_id, client_secret = get_spotify_credentials(env_path)
    if not client_id or not client_secret:
        print(f"Error: Missing Spotify API credentials in {env_path} or environment variables.")
        print("Please ensure Client_ID and Client_secret are set.")
        sys.exit(1)

    tokens = load_tokens(user_id)

    if login or not tokens:
        print(f"Initiating OAuth login for user {user_id}...")
        tokens = run_oauth_login(client_id, client_secret, user_id)

    if tokens.get("expires_at") and time.time() >= tokens["expires_at"]:
        print("Access token expired. Refreshing token...")
        tokens = refresh_access_token(client_id, client_secret, user_id, tokens["refresh_token"])

    access_token = tokens.get("access_token")
    if not access_token:
        print("Error: No valid access token found.")
        sys.exit(1)

    window = None
    if start_day:
        window = (start_day.replace(tzinfo=timezone.utc), (end_day + timedelta(days=1)).replace(tzinfo=timezone.utc))
        print(f"Fetching plays for {user_id} between {start_day:%Y-%m-%d} and {end_day:%Y-%m-%d} (UTC) via Spotify API...")
        items, reached = fetch_items_for_window(access_token, *window)
        if not reached:
            print("Warning: Spotify's history ended before the start of that window, so the earliest "
                  "part of it is not available from the API.")
    else:
        print(f"Fetching recently played tracks for {user_id} via Spotify API...")
        items = fetch_recently_played_api(access_token).get("items", [])
    print(f"Retrieved {len(items)} tracks from Spotify API.")

    # Auto-catalog any new tracks dynamically
    raw_tracks = []
    for item in items:
        track = item.get("track", {})
        track_uri = track.get("uri") or f"spotify:track:{track.get('id')}"
        if track_uri:
            raw_tracks.append({
                "track_id": track_uri,
                "track_name": track.get("name"),
                "artist": track.get("artists", [{}])[0].get("name") if track.get("artists") else "Unknown Artist",
                "album": track.get("album", {}).get("name") if track.get("album") else "Single",
                "ms_played": track.get("duration_ms", 0)
            })

    if raw_tracks:
        try:
            from catalog_utils import register_new_tracks
            new_cat_count = register_new_tracks(raw_tracks)
            if new_cat_count > 0:
                print(f"Auto-cataloged {new_cat_count} new track(s) into catalog.json and real_catalog_extract.json")
        except Exception as e:
            print(f"Warning: Failed to auto-catalog tracks: {e}")

    events_by_day = {}
    for item in items:
        evt = transform_api_item(item, user_id)
        if not evt:
            continue
        day_str = evt["played_at"][:10]
        if day_str not in events_by_day:
            events_by_day[day_str] = []
        events_by_day[day_str].append(evt)

    real_info = {}
    for day_str, evts in sorted(events_by_day.items()):
        real_info[day_str] = write_or_merge_partition(day_str, evts, output_dir)
    total_added = sum(r["added"] for r in real_info.values())
    print(f"API pull complete. Merged {total_added} new events across {len(events_by_day)} partitions into {output_dir}/")

    if window:
        missing = [d for d in (start_day + timedelta(days=i) for i in range((end_day - start_day).days + 1))
                   if f"{d:%Y-%m-%d}" not in events_by_day]
        if missing:
            print("No API events for: " + ", ".join(f"{d:%Y-%m-%d}" for d in missing)
                  + " (plays that old have likely dropped out of Spotify's recent-history window)")

    synth_info = {}
    synth_kept = set()
    if with_synthetic:
        if window:
            n_days = (end_day - start_day).days + 1
            synth_days = [start_day + timedelta(days=i) for i in range(n_days)]
        else:
            synth_days = [datetime.strptime(d, "%Y-%m-%d") for d in sorted(events_by_day)]
        if not regenerate_synthetic:
            kept_days = [d for d in synth_days if has_persona_rows(output_dir, f"{d:%Y-%m-%d}")]
            synth_kept = {f"{d:%Y-%m-%d}" for d in kept_days}
            synth_days = [d for d in synth_days if f"{d:%Y-%m-%d}" not in synth_kept]
            if synth_kept:
                print(f"Persona-matched rows already exist for {len(synth_kept)} day(s); leaving them as they are "
                      f"(use --regenerate-synthetic to replace).")
        if synth_days:
            import generate_data_v2 as gen
            gen.OUTPUT_DIR = output_dir
            _, written = gen.generate_for_days(synth_days, seed=seed if seed is not None else gen.RANDOM_SEED,
                                               scope="persona")
            synth_info = {w["partition"][3:]: w for w in written}
        elif not synth_kept:
            print("No days to generate persona-matched events for (the API returned no plays).")

    report_updated_partitions(real_info, synth_info, synth_kept)


def report_updated_partitions(real_info, synth_info, synth_kept=frozenset()):
    """List every partition this run changed, so you know which dt= folders to re-upload."""
    def changed(day_str):
        real, synth = real_info.get(day_str), synth_info.get(day_str)
        return bool((real and (real["created"] or real["added"])) or synth)

    days = sorted(set(real_info) | set(synth_info) | set(synth_kept))
    updated = [d for d in days if changed(d)]
    unchanged = [d for d in days if not changed(d)]
    if not updated:
        print("\nNo partitions changed.")
    else:
        print(f"\nPartitions updated ({len(updated)}):")
        print(f"  {'partition':<14} {'status':<8} {'real_api':>9} {'persona_matched':>16} {'rows in file':>13}")
        for day_str in updated:
            real, synth = real_info.get(day_str), synth_info.get(day_str)
            created = real["created"] if real else synth["created"]
            total = synth["total"] if synth else real["total"]
            persona = str(synth["generated"]) if synth else ("kept" if day_str in synth_kept else "-")
            print(f"  dt={day_str:<11} {'NEW' if created else 'UPDATED':<8} "
                  f"{('+%d' % real['added']) if real else '-':>9} {persona:>16} {total:>13}")
        print("  files: output/raw/dt=<partition>/events.json \u2014 re-upload these folders to the Volume.")
    if unchanged:
        print("  unchanged: " + ", ".join(f"dt={d}" for d in unchanged))


def parse_day(value):
    try:
        return datetime.strptime(value, "%Y-%m-%d")
    except ValueError:
        raise argparse.ArgumentTypeError(f"'{value}' is not a YYYY-MM-DD date")


def parse_args():
    parser = argparse.ArgumentParser(description="Fetch live recently-played tracks via Spotify Web API.")
    parser.add_argument("--user-id", required=True, help="Pseudonym ID for user")
    parser.add_argument("--login", action="store_true", help="Trigger interactive OAuth login flow")
    parser.add_argument("--env-file", default=".env", help="Path to .env credentials file")
    parser.add_argument("--output-dir", default="output/raw", help="Target landing directory")
    parser.add_argument("--date", type=parse_day, help="Only fetch this UTC date (YYYY-MM-DD)")
    parser.add_argument("--start", type=parse_day, help="First UTC date to fetch (use with --end)")
    parser.add_argument("--end", type=parse_day, help="Last UTC date to fetch, inclusive (use with --start)")
    parser.add_argument("--no-synthetic", action="store_true",
                        help="Skip generating synthetic_persona_matched events for the same days")
    parser.add_argument("--regenerate-synthetic", action="store_true",
                        help="Replace persona-matched rows even on days that already have them")
    parser.add_argument("--seed", type=int, default=None,
                        help="Generator seed for the persona rows (default: generate_data_v2's default)")
    args = parser.parse_args()

    if args.date and (args.start or args.end):
        parser.error("use either --date or --start/--end, not both")
    if bool(args.start) != bool(args.end):
        parser.error("--start and --end go together")
    if args.date:
        args.start = args.end = args.date
    if args.start and args.end < args.start:
        parser.error("--end is before --start")
    return args


if __name__ == "__main__":
    args = parse_args()
    process_live_api_fetch(args.user_id, login=args.login, env_path=args.env_file, output_dir=args.output_dir,
                           start_day=args.start, end_day=args.end,
                           with_synthetic=not args.no_synthetic, seed=args.seed,
                           regenerate_synthetic=args.regenerate_synthetic)